# Generated by Django 4.0.2 on 2022-02-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WasteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('battery', 'battery'), ('biological', 'biological'), ('brown_glass', 'brown_glass'), ('cardboard', 'cardboard'), ('clothes', 'clothes'), ('green_glass', 'green_class'), ('metal', 'metal'), ('paper', 'paper'), ('plastic', 'plastic'), ('shoes', 'shoes'), ('trash', 'trash'), ('white_glass', 'white_glass')], max_length=50)),
                ('desc', models.CharField(blank=True, max_length=1024, null=True)),
                ('recyclable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('area', models.CharField(choices=[('Ajax', 'Ajax'), ('Aurora', 'Aurora'), ('Brampton', 'Brampton'), ('Brock', 'Brock'), ('Burlington', 'Burlington'), ('Caledon', 'Caledon'), ('Clarington', 'Clarington'), ('EastGwillimbury', 'EastGwillimbury'), ('Georgina', 'Georgina'), ('HaltonHills', 'HaltonHills'), ('King', 'King'), ('Markham', 'Markham'), ('Milton', 'Milton'), ('Mississauga', 'Mississauga'), ('Newmarket', 'Newmarket'), ('Oakville', 'Oakville'), ('Oshawa', 'Oshawa'), ('Pickering', 'Pickering'), ('RichmondHill', 'RichmondHill'), ('Scugog', 'Scugog'), ('Toronto', 'Toronto'), ('Uxbridge', 'Uxbridge'), ('Vaughan', 'Vaughan'), ('Whitby', 'Whitby'), ('WhitchurchStouffville', 'WhitchurchStouffville')], max_length=50)),
                ('category', models.ManyToManyField(to='internal.WasteCategory')),
            ],
        ),
    ]
